In [2]:
import numpy as np

a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [5]:
b.shape

(2, 4)

In [6]:
b.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [7]:
b.reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
import pandas as pd

In [9]:
names = ["Deven", "John", "Alice", "Pooja"]
marks = [95, 84, 45, 100]

In [49]:
classroom = pd.DataFrame({"names": names, "marks": marks})

In [50]:
classroom

names  marks
0  Deven     95
1   John     84
2  Alice     45
3  Pooja    100

In [73]:
grades = ["D", "C", "B", "A"]
marks_between = sorted([100, 90, 60, 40, 20])
print(marks_between)

[20, 40, 60, 90, 100]


In [74]:
classroom["grade"] = pd.cut(classroom["marks"], bins=marks_between, labels=grades)

In [75]:
classroom

names  marks grade
0  Deven     95     A
1   John     84     B
2  Alice     45     C
3  Pooja    100     A

In [76]:
classroom["countries"] = ["India", "USA", "France", "Pakistan"]

In [77]:
classroom

names  marks grade countries
0  Deven     95     A     India
1   John     84     B       USA
2  Alice     45     C    France
3  Pooja    100     A  Pakistan

In [79]:
classroom.groupby("countries", "names").mean

ValueError: No axis named names for object type DataFrame

In [82]:
L = [0, 1, 2, 0]
classroom.groupby(L).sum()

TypeError: category type does not support sum operations

In [83]:
monte = pd.Series(
    [
        "Graham Chapman",
        "John Cleese",
        "Terry Gilliam",
        "Eric Idle",
        "Terry Jones",
        "Michael Palin",
    ]
)

In [90]:
lower = monte.str.lower()

In [85]:
monte.str.len()

0    14
1    11
2    13
3     9
4    11
5    13
dtype: int64

In [91]:
[x for x in lower]

['graham chapman',
 'john cleese',
 'terry gilliam',
 'eric idle',
 'terry jones',
 'michael palin']

In [120]:
lower.str.replace("eric", "deven", regex=True)

0    graham chapman
1       john cleese
2     terry gilliam
3        deven idle
4       terry jones
5     michael palin
dtype: object

In [123]:
a = monte.str.lower().str.split()

In [124]:
type(a)

pandas.core.series.Series

In [131]:
a

0    [graham, chapman]
1       [john, cleese]
2     [terry, gilliam]
3         [eric, idle]
4       [terry, jones]
5     [michael, palin]
dtype: object

In [132]:
a[:2]

0    [graham, chapman]
1       [john, cleese]
dtype: object

In [134]:
a = dict(a)

In [136]:
for value in a.values():
    print(f"FirstName: {value[0]}, LastName: {value[1]}")

FirstName: graham, LastName: chapman
FirstName: john, LastName: cleese
FirstName: terry, LastName: gilliam
FirstName: eric, LastName: idle
FirstName: terry, LastName: jones
FirstName: michael, LastName: palin


In [139]:
monte.str.split().str[0] + " " + monte.str.split().str[1]

0    Graham Chapman
1       John Cleese
2     Terry Gilliam
3         Eric Idle
4       Terry Jones
5     Michael Palin
dtype: object

In [142]:
titanic = pd.read_csv("../../data/titanic/train.csv")
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [143]:
print(titanic.shape)

(891, 12)


In [167]:
titanic = titanic.dropna(thresh=10)

In [147]:
titanic.groupby("Survived").count()

PassengerId  Pclass  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Survived                                                                    
0                 549     549   549  549  424    549    549     549   549   
1                 342     342   342  342  290    342    342     342   342   

          Cabin  Embarked  
Survived                   
0            68       549  
1           136       340

In [153]:
females = titanic["Survived"].groupby(titanic["Sex"]).count()

In [154]:
females

Sex
female    314
male      577
Name: Survived, dtype: int64

In [156]:
count = titanic.groupby("Sex")[["Survived"]].count()
mean = titanic.groupby("Sex")[["Survived"]].mean()

In [160]:
print(count)
print("\n\n")
print(mean)

        Survived
Sex             
female       314
male         577



        Survived
Sex             
female  0.742038
male    0.188908


In [161]:
count

Survived
Sex             
female       314
male         577

In [162]:
mean

Survived
Sex             
female  0.742038
male    0.188908

In [168]:
titanic.groupby(["Sex", "Pclass"])["Survived"].aggregate("count").unstack()

Pclass    1    2    3
Sex                  
female   94   76  144
male    122  108  347

In [169]:
titanic[:200]

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
195          196         1       1   
196          197         0       3   
197          198         0       3   
198          199         1       3   
199          200         0       2   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
195                               Lurette, Miss. Elise  female  58.0      0   
196                                Mernagh, Mr. Robert    male   NaN      0   
197                   Olsen, Mr. Karl Siegwart Andreas    male  42.0      0   
198                   Madigan, Miss. Margaret 'Maggie'  female   NaN      0   
199             Yrois, Miss. Henriette ('Mrs Harbeck')  female  24.0      0   

     Parch            Ticket      Fare Cabin Embarked  
0        0         A/5 21171    7.2500   NaN        S  
1        0          PC 17599   71.2833   C85        C  
2        0  STON/O2. 3101282    7.9250   NaN        S  
3        0            113803   53.1000  C123        S  
4        0            373450    8.0500   NaN        S  
..     ...               ...       ...   ...      ...  
195      0          PC 17569  146.5208   B80        C  
196      0            368703    7.7500   NaN        Q  
197      1              4579    8.4042   NaN        S  
198      0            370370    7.7500   NaN        Q  
199      0            248747   13.0000   NaN        S  

[200 rows x 12 columns]

In [174]:
"N/A" in titanic["Cabin"]

False

In [175]:
age = pd.cut(titanic["Age"], [0, 18, 80])
titanic.pivot_table("Survived", ["Sex", age], "Pclass")

/var/folders/xn/4bc_bn4140ngpppx3_1k_3n00000gn/T/ipykernel_13372/145527605.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table('Survived', ['Sex',age],'Pclass')


Pclass                  1         2         3
Sex    Age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663